#!/usr/bin/env python3

import argparse
import csv
import json
from pathlib import Path
from statistics import mean, pstdev
from typing import Any, Dict, List, Optional


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize gimbal calibration samples.csv into summary.json."
    )
    parser.add_argument(
        "--csv-path",
        required=True,
        help="Path to samples.csv generated by gimbal_calibration.",
    )
    parser.add_argument(
        "--summary-path",
        default=None,
        help="Optional output path. Defaults to summary.json next to the CSV.",
    )
    return parser.parse_args()


def load_samples(csv_path: Path) -> List[Dict[str, str]]:
    with csv_path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _float_or_none(value: Optional[str]) -> Optional[float]:
    if value in (None, "", "None"):
        return None
    return float(value)


def _summary_stats(values: List[float]) -> Dict[str, Any]:
    if not values:
        return {"mean": None, "std": None, "count": 0}
    if len(values) == 1:
        return {"mean": values[0], "std": 0.0, "count": 1}
    return {"mean": mean(values), "std": pstdev(values), "count": len(values)}


def summarize_verification(rows: List[Dict[str, str]]) -> Dict[str, object]:
    result: Dict[str, object] = {}
    for axis, encoder_key in (("yaw", "encoder_yaw_deg"), ("pitch", "encoder_pitch_deg")):
        positive = next(
            (
                row for row in rows
                if row["phase"] == "verification"
                and row["axis"] == axis
                and row["sweep_direction"] == "positive"
            ),
            None,
        )
        negative = next(
            (
                row for row in rows
                if row["phase"] == "verification"
                and row["axis"] == axis
                and row["sweep_direction"] == "negative"
            ),
            None,
        )
        pos_value = _float_or_none(positive.get(encoder_key)) if positive else None
        neg_value = _float_or_none(negative.get(encoder_key)) if negative else None
        sign_ok = None
        if pos_value is not None and neg_value is not None:
            sign_ok = pos_value > neg_value
        result[axis] = {
            "positive_sample_deg": pos_value,
            "negative_sample_deg": neg_value,
            "positive_increases_encoder": sign_ok,
        }
    return result


def summarize_hysteresis(rows: List[Dict[str, str]]) -> Dict[str, object]:
    result: Dict[str, object] = {"yaw": None, "pitch": None}
    for axis, encoder_key in (("yaw", "encoder_yaw_deg"), ("pitch", "encoder_pitch_deg")):
        forward = {
            _float_or_none(row["commanded_deg"]): _float_or_none(row[encoder_key])
            for row in rows
            if row["phase"] == "sweep"
            and row["axis"] == axis
            and row["sweep_direction"] == "forward"
        }
        reverse = {
            _float_or_none(row["commanded_deg"]): _float_or_none(row[encoder_key])
            for row in rows
            if row["phase"] == "sweep"
            and row["axis"] == axis
            and row["sweep_direction"] == "reverse"
        }
        diffs = []
        for commanded in set(forward.keys()) & set(reverse.keys()):
            if commanded is None or forward[commanded] is None or reverse[commanded] is None:
                continue
            diffs.append(abs(forward[commanded] - reverse[commanded]))
        if diffs:
            result[axis] = max(diffs)
    return result


def summarize_zero_offsets(rows: List[Dict[str, str]]) -> Dict[str, object]:
    result: Dict[str, object] = {}
    for axis, encoder_key, camera_key in (
        ("yaw", "encoder_yaw_deg", "camera_yaw_deg"),
        ("pitch", "encoder_pitch_deg", "camera_pitch_deg"),
        ("roll", "encoder_roll_deg", "camera_roll_deg"),
    ):
        offsets = []
        for row in rows:
            if row["phase"] != "zero_offset":
                continue
            encoder_value = _float_or_none(row.get(encoder_key))
            camera_value = _float_or_none(row.get(camera_key))
            if encoder_value is None or camera_value is None:
                continue
            offsets.append(encoder_value - camera_value)
        result[axis] = _summary_stats(offsets)
    return result


def write_summary_json(path: Path, summary: Dict[str, object]) -> None:
    path.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    csv_path = Path(args.csv_path)
    rows = load_samples(csv_path)
    summary: Dict[str, Any] = {
        "sample_count": len(rows),
        "verification": summarize_verification(rows),
        "hysteresis_max_deg": summarize_hysteresis(rows),
        "zero_offset_deg": summarize_zero_offsets(rows),
        "source_csv": str(csv_path),
    }
    summary_path = Path(args.summary_path) if args.summary_path else csv_path.with_name("summary.json")
    write_summary_json(summary_path, summary)
    print(f"Wrote {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
